### ISSUE TITLE
Control.option()

### ISSUE THREAD

**Issue by ruslansennov** [vavr-io/vavr-kotlin#10]
I believe this should be removed because it is not vavr-way: we accept nulls everywhere
/cc @danieldietrich @zvozin 

```kotlin
/**
 * Creates an Option of a nullable.
 * @return None() for null, Some(this) for a present value
 */
fun <A> A?.option():
        Option<A> = if (this == null) none() else some(this)
```

**Comment by danieldietrich** [comment]
How is it read? Is this an extension method for objects of type 'A' ?

If so, what means 'this' in this context. Is it the current instance of 'A' ?

If so, A has to possibly null, otherwise the `if (this == null)` case will never be true.

**Comment by ruslansennov** [comment]
>  Is this an extension method for objects of type 'A' ?

Yes. In Kotlin 
```kotlin
val v: Option<Any> = null.option()
```
is valid expression

**Comment by danieldietrich** [comment]
Then it has to be `fun <A> A.option()`

**Comment by ruslansennov** [comment]
No :) 
`A.option()` extends non-nullable objects, instead of `A?.option()` that extends nullables

**Comment by danieldietrich** [comment]
Aargh 😆 right!

But then your first code block looks good, doesn't it?

**Comment by ruslansennov** [comment]
Cited code block is in repo already. Yes, it works but looks not so good. It is very similar to our removed static method `Option.of()` which looked like 
```java
Option<T> of(T v) {
  return v == null ? none() : some(v);
}
```
In vavr we removed this method a long time ago, but kept `none()` and `some()`

**Comment by zvozin** [comment]
What's the actual issue with it? (your example doesn't add up - `Any` is
not nullable).

**Comment by danieldietrich** [comment]
What!? No, we did not remove it. This is a copy from the current master:

```java
    /**
     * Creates a new {@code Option} of a given value.
     *
     * @param value A value
     * @param <T>   type of the value
     * @return {@code Some(value)} if value is not {@code null}, {@code None} otherwise
     */
    static <T> Option<T> of(T value) {
        return (value == null) ? none() : some(value);
    }
```

We need such a method because at runtime we do not know if an object is null or not. There is no way to achieve the same result when only having none() and some(T) (other that checking for null using if).

**Comment by ruslansennov** [comment]
Sorry guys, my fault

**Comment by danieldietrich** [comment]
Thx for asking!
