### ISSUE TITLE
Release Jar?

### ISSUE THREAD

**Issue by FrederikNJS** [vavr-io/vavr-kotlin#9]
I have been looking for a built JAR I can easily import into my project using gradle, but have not been able to find one.

Would it be possible to publish a jar?

**Comment by danieldietrich** [comment]
Hi Frederik, it is still in the make. Currently I'm on vacation (until Sep). After that we can release a preview.

**Comment by FrederikNJS** [comment]
Awesome, can't wait :+1:

**Comment by ruslansennov** [comment]
you can try [the snapshot version](https://oss.sonatype.org/content/repositories/snapshots/io/vavr/vavr-kotlin/)

**Comment by ruslansennov** [comment]
released
